import type { PullRequest } from "../types/dashboard";

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

function daysAgo(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

export const ASSIGNED_TO_ME: PullRequest[] = [
  {
    id: 1,
    title: "Add real-time collaboration cursors to canvas editor",
    number: 1847,
    repo: "acme/frontend",
    author: "sarahchen",
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(4),
    isDraft: false,
    labels: [
      { name: "feature", color: "#1d76db" },
      { name: "frontend", color: "#7057ff" },
    ],
    reviewStatus: "pending",
    reviewers: [
      { username: "you", status: "pending" },
      { username: "dkim", status: "approved" },
    ],
    additions: 284,
    deletions: 51,
    url: "https://github.com/acme/frontend/pull/1847",
  },
  {
    id: 2,
    title: "Fix memory leak in WebSocket reconnection handler",
    number: 1832,
    repo: "acme/backend",
    author: "alexmartinez",
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(1),
    isDraft: false,
    labels: [
      { name: "bug", color: "#d73a4a" },
      { name: "critical", color: "#b60205" },
    ],
    reviewStatus: "changes_requested",
    reviewers: [
      { username: "you", status: "changes_requested" },
      { username: "mwilson", status: "pending" },
    ],
    additions: 42,
    deletions: 18,
    url: "https://github.com/acme/backend/pull/1832",
  },
  {
    id: 3,
    title: "Implement rate limiting for API v2 endpoints",
    number: 1851,
    repo: "acme/api-gateway",
    author: "jpark",
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(8),
    isDraft: false,
    labels: [
      { name: "security", color: "#fbca04" },
      { name: "api", color: "#006b75" },
    ],
    reviewStatus: "pending",
    reviewers: [{ username: "you", status: "pending" }],
    additions: 156,
    deletions: 23,
    url: "https://github.com/acme/api-gateway/pull/1851",
  },
  {
    id: 4,
    title: "Update onboarding flow with new design tokens",
    number: 1839,
    repo: "acme/frontend",
    author: "emilyw",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
    isDraft: true,
    labels: [
      { name: "design", color: "#e99695" },
      { name: "ux", color: "#c2e0c6" },
    ],
    reviewStatus: "pending",
    reviewers: [
      { username: "you", status: "pending" },
      { username: "sarahchen", status: "pending" },
    ],
    additions: 445,
    deletions: 312,
    url: "https://github.com/acme/frontend/pull/1839",
  },
  {
    id: 5,
    title: "Migrate user preferences to new database schema",
    number: 1828,
    repo: "acme/backend",
    author: "dkim",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(2),
    isDraft: false,
    labels: [
      { name: "database", color: "#5319e7" },
      { name: "migration", color: "#bfd4f2" },
    ],
    reviewStatus: "pending",
    reviewers: [
      { username: "you", status: "pending" },
      { username: "alexmartinez", status: "approved" },
      { username: "mwilson", status: "pending" },
    ],
    additions: 89,
    deletions: 67,
    url: "https://github.com/acme/backend/pull/1828",
  },
  {
    id: 6,
    title: "Add CSV export for analytics dashboard",
    number: 1856,
    repo: "acme/frontend",
    author: "mwilson",
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(2),
    isDraft: false,
    labels: [{ name: "feature", color: "#1d76db" }],
    reviewStatus: "approved",
    reviewers: [
      { username: "you", status: "approved" },
      { username: "emilyw", status: "approved" },
    ],
    additions: 198,
    deletions: 12,
    url: "https://github.com/acme/frontend/pull/1856",
  },
  {
    id: 7,
    title: "Fix race condition in payment webhook processing",
    number: 1843,
    repo: "acme/payments",
    author: "tomr",
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(12),
    isDraft: false,
    labels: [
      { name: "bug", color: "#d73a4a" },
      { name: "payments", color: "#d93f0b" },
    ],
    reviewStatus: "pending",
    reviewers: [
      { username: "you", status: "pending" },
      { username: "jpark", status: "commented" },
    ],
    additions: 34,
    deletions: 19,
    url: "https://github.com/acme/payments/pull/1843",
  },
];

export const TEAM_PRS: PullRequest[] = [
  {
    id: 8,
    title: "Refactor authentication middleware to support OIDC",
    number: 1844,
    repo: "acme/api-gateway",
    author: "sarahchen",
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(3),
    isDraft: false,
    labels: [
      { name: "refactor", color: "#cfd3d7" },
      { name: "auth", color: "#e4e669" },
    ],
    reviewStatus: "changes_requested",
    reviewers: [
      { username: "tomr", status: "changes_requested" },
      { username: "rgupta", status: "pending" },
    ],
    additions: 312,
    deletions: 198,
    url: "https://github.com/acme/api-gateway/pull/1844",
  },
  {
    id: 9,
    title: "Add integration tests for billing module",
    number: 1858,
    repo: "acme/billing",
    author: "dkim",
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(1),
    isDraft: false,
    labels: [{ name: "testing", color: "#0075ca" }],
    reviewStatus: "pending",
    reviewers: [{ username: "mwilson", status: "pending" }],
    additions: 567,
    deletions: 23,
    url: "https://github.com/acme/billing/pull/1858",
  },
  {
    id: 10,
    title: "Implement dark mode toggle with system preference detection",
    number: 1836,
    repo: "acme/frontend",
    author: "mwilson",
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(6),
    isDraft: false,
    labels: [
      { name: "feature", color: "#1d76db" },
      { name: "design", color: "#e99695" },
    ],
    reviewStatus: "approved",
    reviewers: [
      { username: "emilyw", status: "approved" },
      { username: "sarahchen", status: "approved" },
    ],
    additions: 234,
    deletions: 89,
    url: "https://github.com/acme/frontend/pull/1836",
  },
  {
    id: 11,
    title: "Update GraphQL schema for workspace API v3",
    number: 1822,
    repo: "acme/api-gateway",
    author: "jpark",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
    isDraft: false,
    labels: [
      { name: "api", color: "#006b75" },
      { name: "graphql", color: "#e10098" },
    ],
    reviewStatus: "pending",
    reviewers: [
      { username: "alexmartinez", status: "pending" },
      { username: "tomr", status: "pending" },
    ],
    additions: 456,
    deletions: 134,
    url: "https://github.com/acme/api-gateway/pull/1822",
  },
  {
    id: 12,
    title: "Optimize full-text search index performance",
    number: 1849,
    repo: "acme/search",
    author: "alexmartinez",
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(5),
    isDraft: false,
    labels: [{ name: "performance", color: "#ff7619" }],
    reviewStatus: "pending",
    reviewers: [
      { username: "dkim", status: "commented" },
      { username: "jpark", status: "pending" },
    ],
    additions: 78,
    deletions: 45,
    url: "https://github.com/acme/search/pull/1849",
  },
];

export const NEEDS_TEAM_REVIEW: PullRequest[] = [
  {
    id: 13,
    title: "Add SAML SSO integration for enterprise customers",
    number: 1840,
    repo: "acme/auth",
    author: "ext-sso-dev",
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(8),
    isDraft: false,
    labels: [
      { name: "feature", color: "#1d76db" },
      { name: "enterprise", color: "#6f42c1" },
    ],
    reviewStatus: "pending",
    reviewers: [{ username: "sarahchen", status: "commented" }],
    additions: 789,
    deletions: 56,
    url: "https://github.com/acme/auth/pull/1840",
  },
  {
    id: 14,
    title: "Upgrade to Node 22 LTS across all services",
    number: 1853,
    repo: "acme/infrastructure",
    author: "devops-bot",
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(14),
    isDraft: false,
    labels: [
      { name: "dependencies", color: "#0366d6" },
      { name: "infrastructure", color: "#008672" },
    ],
    reviewStatus: "pending",
    reviewers: [],
    additions: 23,
    deletions: 23,
    url: "https://github.com/acme/infrastructure/pull/1853",
  },
  {
    id: 15,
    title: "Implement audit logging for admin panel actions",
    number: 1835,
    repo: "acme/api-gateway",
    author: "security-team",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
    isDraft: false,
    labels: [
      { name: "security", color: "#fbca04" },
      { name: "compliance", color: "#b8860b" },
    ],
    reviewStatus: "commented",
    reviewers: [
      { username: "jpark", status: "commented" },
      { username: "alexmartinez", status: "pending" },
    ],
    additions: 345,
    deletions: 12,
    url: "https://github.com/acme/api-gateway/pull/1835",
  },
  {
    id: 16,
    title: "Improve form component accessibility with ARIA labels",
    number: 1848,
    repo: "acme/ui-library",
    author: "a11y-team",
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(10),
    isDraft: false,
    labels: [
      { name: "accessibility", color: "#0e8a16" },
      { name: "design-system", color: "#d876e3" },
    ],
    reviewStatus: "pending",
    reviewers: [{ username: "emilyw", status: "pending" }],
    additions: 167,
    deletions: 89,
    url: "https://github.com/acme/ui-library/pull/1848",
  },
];
